AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 3.1

  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature', 'resource', 'desc', 'task']

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/HashSyntax:
  Enabled: false
