AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.6

  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'resource', 'desc', 'task']

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false
