sudo: false
language: ruby
rvm:
  - 2.6.2
before_install: gem install bundler
before_script:
  - export database_user=postgres
  - psql -c 'create database finances_test;' -U postgres
script:
  - bundle exec rubocop
  - bundle exec rspec
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: KlXBPRSolvoQbKi3fueEHh3VY6wOJn4969yODBH91olGMP0FHg+S9cfTSsXcN/RKyy6cat5dw1vqmrOBINzuyq0BDPD4vAgCUETcL90p+vZlVK2rf0tn8xJtRZLGeJKugTKS+ZNY72ipNoqimDrFQUxLQy7jsD4XQvwO8WrqS21oklloB2X8F29kINcT55LX1rOs4xxZvAPln0ntwOnnTKQObfIfbZo1XOvs1VJylfyvE4ZRnFASZT2/PT2RY4iIqsKAvf7Wqd1NIrS0TbIRSgMl5ZsRQ0SfcRXvKaq2JwlDD0zgAgKWZVDNzercNeuDiiavvQBJyp0f5FbDqdpZFpNMRTO6kxSZ+RL2d5YAIvgNzl5rz/0tLId0buiXp8M6tdxp0jEhjf3GTq2/ETx5Dxvb2v8wRkXZnBZWxMlXjSN29TzTHHLjNJs8MP9maiMZqKTqa+k3CtZT/cVYhD6MyL0wQAgmfKRZyrt5Zo+jPfEYi6tg4osKZXg9qh/WR3SajnvrtltyTxNKJMny+V5ojjWCssUs6Q4O3hyWTnz7ODC746zLBm3QamGARy4eAVaTX+9uczHfdMJZYcRetDtVfPPKbsrKHAQ2RVYgzKmz4q/7yKxdUwSQFW9G+NYeFZ93QuOy7wuw9hnHvFtUnpewKlaQ+/9yztideoDslTRAKwg=
  app: financesapi
