sudo: false
language: ruby
rvm:
  - 2.6.5
env:
  - SECRET_KEY_BASE="jQTTcSfTmCunpVgMmQu1UkYYzA2b0mvR4eormkUkMtxxpSeSKJWTYJJSU6vQwqG"
before_install: gem install bundler
before_script:
  - export database_user=postgres
  - psql -c 'create database finances_test;' -U postgres
script:
  - bundle exec rubocop
  - bundle exec rspec
services:
  - postgresql
