version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
        context: ./docker
        args:
          - RUBY_VERSION=2.7.3
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY_BASE=V2ZxX0apQv98WoGLoRwhXE2fURe6sNi6bW2PoONt8AlHZ1OyeZYpdYmFB1MVkyD
      - CORS_ORIGINS=localhost:8080
    entrypoint: docker/entrypoint.sh
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/finances-api:cached
    tty: true
    stdin_open: true

volumes:
    gems:
    postgres:
    rails_cache:
