version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
        context: ./docker
        args:
          - RUBY_VERSION=2.6.5
          - BUNDLE_JOBS=15
          - BUNDLE_RETRY=2
          - NODE_VERSION=12
          - UID=500
          - GID=500
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY_BASE=V2ZxX0apQv98WoGLoRwhXE2fURe6sNi6bW2PoONt8AlHZ1OyeZYpdYmFB1MVkyD
    entrypoint: docker/entrypoint.sh
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/finances-api:cached
      - gems:/gems
      - rails_cache:/finances-api/tmp/cache
    user: ruby
    tty: true
    stdin_open: true

volumes:
    gems:
    postgres:
    rails_cache:
