version: 2.1
commands:
  checkout_and_bundle_install:
    description: "Checkout the code and bundle install"
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            gem install bundler

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

orbs:
  bundle-install: toshimaru/bundle-install@0.3.1
workflows:
  rspec:
    jobs:
      - rubocop
      - rspec

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers

    steps:
      - checkout_and_bundle_install

      - run:
          name: Run rubocop checks
          command: bundle exec rubocop
          
  rspec:
    parallelism: 2
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 2
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:@localhost/finances_test
          SECRET_KEY_BASE: V2ZxX0apQv98WoGLoRwhXE2fURe6sNi6bW2PoONt8AlHZ1OyeZYplYmFB1MVkyD
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: finances_test
          POSTGRES_PASSWORD: ""
          SECRET_KEY_BASE: V2ZxX0apQv98WoGLoRwhXE2fURe6sNi6bW2PoONt8AlHZ1OyeZYplYmFB1MVkyD

    steps:
      - checkout_and_bundle_install

      - run:
          name: Update binaries
          command: sudo apt-get update && sudo apt-get install -y ghostscript xvfb libfontconfig

      - run:
          name: Run rspec in parallel
          command: bundle exec rspec
