default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finances_development
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  host: localhost
  port: 5432
test:
  <<: *default
  database: finances_test

production:
  <<: *default
  database: finances_production
  username: finances
  password: <%= ENV['FINANCES_DATABASE_PASSWORD'] %>
